spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenbingyin/spring-cloud-action
          search-paths:
          username:
          password:

server:
  port: 7001